version: '3.8'

services:
  # Base de datos PostgreSQL
  database:
    image: postgres:15
    container_name: hotel_db
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel_network

  # Backend Laravel
  backend:
    build:
      context: ./Recuperacion
      dockerfile: Dockerfile
    container_name: hotel_backend
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DATABASE=hotel
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    ports:
      - "8000:80"
    depends_on:
      - database
    volumes:
      - ./Recuperacion:/var/www/html
    networks:
      - hotel_network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hotel_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hotel_network

volumes:
  postgres_data:

networks:
  hotel_network:
    driver: bridge