version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: maikel434/hotel-backend:latest
    ports:
      - "8000:8000"
    environment:
      DB_HOST: database
      DB_DATABASE: hotel
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - database

  frontend:
    image: maikel434/hotel-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: